- name: Get some needed facts and prepare for playbook
  hosts: all
  become: false
  tasks:
  - name: set ssh port to wait for if reboot is required
    set_fact:
      ansible_port: 22
    when:
    - ansible_ssh_port is not defined

  - name: create log directory
    delegate_to: localhost
    run_once: true
    file:
      path: "{{ playbook_dir }}/log"
      state: directory
      mode: 0750
    when:
    - update_logs
